export const initialDepartments = [
  { id: 'dept-1', name: 'Engineering', code: 'ENG', head: 'Alex Morgan', employeeCount: 14, budget: '$450,000', icon: 'Code', color: 'blue' },
  { id: 'dept-2', name: 'Human Resources', code: 'HR', head: 'Sarah Connor', employeeCount: 6, budget: '$180,000', icon: 'Users', color: 'purple' },
  { id: 'dept-3', name: 'Product & Design', code: 'PRD', head: 'Elena Rostova', employeeCount: 8, budget: '$280,000', icon: 'Palette', color: 'pink' },
  { id: 'dept-4', name: 'Marketing', code: 'MKT', head: 'David Miller', employeeCount: 9, budget: '$220,000', icon: 'TrendingUp', color: 'amber' },
  { id: 'dept-5', name: 'Finance', code: 'FIN', head: 'Rachel Green', employeeCount: 5, budget: '$190,000', icon: 'DollarSign', color: 'emerald' },
  { id: 'dept-6', name: 'Sales', code: 'SLS', head: 'Marcus Vance', employeeCount: 11, budget: '$310,000', icon: 'Briefcase', color: 'indigo' },
];

export const initialDesignations = [
  { id: 'desig-1', title: 'Senior Software Engineer', department: 'Engineering', level: 'Level 4 - Senior', count: 6 },
  { id: 'desig-2', title: 'Frontend Developer', department: 'Engineering', level: 'Level 2 - Mid', count: 4 },
  { id: 'desig-3', title: 'DevOps / Cloud Architect', department: 'Engineering', level: 'Level 5 - Lead', count: 4 },
  { id: 'desig-4', title: 'HR Manager', department: 'Human Resources', level: 'Level 4 - Managerial', count: 2 },
  { id: 'desig-5', title: 'Talent Acquisition Lead', department: 'Human Resources', level: 'Level 3 - Lead', count: 4 },
  { id: 'desig-6', title: 'Lead Product Designer', department: 'Product & Design', level: 'Level 4 - Senior', count: 3 },
  { id: 'desig-7', title: 'UI/UX Designer', department: 'Product & Design', level: 'Level 2 - Mid', count: 5 },
  { id: 'desig-8', title: 'Growth Marketing Specialist', department: 'Marketing', level: 'Level 3 - Mid', count: 5 },
  { id: 'desig-9', title: 'Brand & Content Strategist', department: 'Marketing', level: 'Level 2 - Associate', count: 4 },
  { id: 'desig-10', title: 'Senior Financial Analyst', department: 'Finance', level: 'Level 4 - Senior', count: 3 },
  { id: 'desig-11', title: 'Account Executive', department: 'Sales', level: 'Level 3 - Mid', count: 7 },
];

export const initialRoles = [
  {
    id: 'role-1',
    name: 'Super Admin',
    badgeColor: 'purple',
    description: 'Full system control, employee governance, billing, and security settings.',
    permissions: ['All Permissions', 'User Management', 'Payroll Access', 'System Settings', 'Audit Logs'],
    usersCount: 2,
  },
  {
    id: 'role-2',
    name: 'HR Manager',
    badgeColor: 'indigo',
    description: 'Manages onboardings, employee details, departments, designations, and leave requests.',
    permissions: ['Manage Employees', 'Department Config', 'Leave Approvals', 'View Reports'],
    usersCount: 5,
  },
  {
    id: 'role-3',
    name: 'Team Lead',
    badgeColor: 'blue',
    description: 'Direct team supervisory rights, attendance approval, performance reviews.',
    permissions: ['Team Overview', 'Leave Endorsement', 'Task Assignment'],
    usersCount: 9,
  },
  {
    id: 'role-4',
    name: 'Employee',
    badgeColor: 'teal',
    description: 'Standard access to self-service portal, profile update, and company directory.',
    permissions: ['Self Profile', 'Apply Leaves', 'View Directory'],
    usersCount: 35,
  },
  {
    id: 'role-5',
    name: 'Viewer',
    badgeColor: 'slate',
    description: 'Read-only access for auditors or temporary observers.',
    permissions: ['View Only'],
    usersCount: 2,
  },
];

export const initialEmployees = [
  {
    id: 'EMP-1001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@workpulse.io',
    phone: '+91 98765 43210',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    role: 'Team Lead',
    status: 'Active',
    joiningDate: '2023-03-15',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    location: 'Bangalore, IN'
  },
  {
    id: 'EMP-1002',
    name: 'Sarah Connor',
    email: 'sarah.c@workpulse.io',
    phone: '+1 415 555 2671',
    department: 'Human Resources',
    designation: 'HR Manager',
    role: 'HR Manager',
    status: 'Active',
    joiningDate: '2022-01-10',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
    location: 'San Francisco, US'
  },
  {
    id: 'EMP-1003',
    name: 'Elena Rostova',
    email: 'elena.r@workpulse.io',
    phone: '+44 20 7946 0912',
    department: 'Product & Design',
    designation: 'Lead Product Designer',
    role: 'Team Lead',
    status: 'Active',
    joiningDate: '2022-08-01',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    location: 'London, UK'
  },
  {
    id: 'EMP-1004',
    name: 'Vikram Malhotra',
    email: 'vikram.m@workpulse.io',
    phone: '+91 98111 22334',
    department: 'Engineering',
    designation: 'DevOps / Cloud Architect',
    role: 'Super Admin',
    status: 'Active',
    joiningDate: '2021-11-20',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    location: 'Mumbai, IN'
  },
  {
    id: 'EMP-1005',
    name: 'Jessica Chen',
    email: 'jessica.c@workpulse.io',
    phone: '+1 650 332 9981',
    department: 'Marketing',
    designation: 'Growth Marketing Specialist',
    role: 'Employee',
    status: 'On Leave',
    joiningDate: '2023-06-12',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    location: 'New York, US'
  },
  {
    id: 'EMP-1006',
    name: 'David Miller',
    email: 'david.m@workpulse.io',
    phone: '+1 212 990 4421',
    department: 'Marketing',
    designation: 'Brand & Content Strategist',
    role: 'Team Lead',
    status: 'Active',
    joiningDate: '2022-05-18',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    location: 'Austin, US'
  },
  {
    id: 'EMP-1007',
    name: 'Priya Patel',
    email: 'priya.p@workpulse.io',
    phone: '+91 99201 88472',
    department: 'Human Resources',
    designation: 'Talent Acquisition Lead',
    role: 'HR Manager',
    status: 'Active',
    joiningDate: '2023-09-01',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    location: 'Pune, IN'
  },
  {
    id: 'EMP-1008',
    name: 'Rachel Green',
    email: 'rachel.g@workpulse.io',
    phone: '+1 312 443 1928',
    department: 'Finance',
    designation: 'Senior Financial Analyst',
    role: 'Employee',
    status: 'Active',
    joiningDate: '2022-10-15',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    location: 'Chicago, US'
  },
  {
    id: 'EMP-1009',
    name: 'Marcus Vance',
    email: 'marcus.v@workpulse.io',
    phone: '+1 415 776 2001',
    department: 'Sales',
    designation: 'Account Executive',
    role: 'Team Lead',
    status: 'Inactive',
    joiningDate: '2021-04-10',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    location: 'San Francisco, US'
  },
  {
    id: 'EMP-1010',
    name: 'Ananya Roy',
    email: 'ananya.roy@workpulse.io',
    phone: '+91 97723 11223',
    department: 'Product & Design',
    designation: 'UI/UX Designer',
    role: 'Employee',
    status: 'Active',
    joiningDate: '2024-01-15',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    location: 'Hyderabad, IN'
  }
];
